services:
  - type: web
    name: primelift-backend
    env: node
    buildCommand: npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        value: primelift_super_secret_key_2024
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        value: 3306
